version: '3.9'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
     context: .
    environment:
      DB_HOST: postgres-db
      DB_NAME: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
    - "8080:8080"

volumes:
  postgres_data: